import test from 'node:test';
import assert from 'node:assert/strict';
import {freshState,at,addDays,validateState,validatePlacement} from '../shared/planner.mjs';
import {applyAction} from '../shared/actions.mjs';
const today='2026-09-28',now=at(today,480);
function fixture(n=1){const s=freshState();s.settings.days.forEach(d=>{d.slots=[[540,1080]];d.budget=180;d.breakCount=1;d.breakMinutes=15;});for(let i=0;i<n;i++)s.subjects.push({id:`s${i}`,name:`Subject ${i}`,color:'#5274dc'});return s;}
function goal(s,values={}){return applyAction(s,{type:'goal',subjectId:'s0',title:'Cell biology',totalSlides:120,startSlide:1,deadline:addDays(today,13),effort:'normal',...values},now);}
function blocks(s,id=s.goals[0].id){return s.sessions.filter(x=>x.goalId===id&&x.status==='planned');}
function coverage(s,id=s.goals[0].id){const g=s.goals.find(g=>g.id===id);let next=g.startSlide+g.completedSlides;for(const x of blocks(s,id)){assert.equal(x.slideStart,next);assert.ok(x.slideEnd>=x.slideStart);assert.ok(x.date<=g.deadline&&x.date>=g.startDate);next=x.slideEnd+1;}assert.equal(next,g.startSlide+g.totalSlides);}
test('slides span the deadline horizon in contiguous whole ranges',()=>{const s=goal(fixture());coverage(s);assert.ok(blocks(s).some(x=>x.date>addDays(today,6)));assert.equal(blocks(s).at(-1).date,s.goals[0].deadline);for(const x of blocks(s))assert.equal(validatePlacement(s,x),null);});
test('different subjects rotate while respecting effort targets and class time',()=>{let s=fixture(3);s.classes=[{id:'class',day:0,start:600,end:720,name:'School'}];for(let i=0;i<3;i++)s=goal(s,{subjectId:`s${i}`,title:`Goal ${i}`,effort:['light','normal','heavy'][i],totalSlides:500});assert.deepEqual(s.sessions.filter(x=>x.type==='study').slice(0,6).map(x=>x.subjectId),['s0','s1','s2','s0','s1','s2']);for(const g of s.goals)coverage(s,g.id);for(const x of s.sessions)assert.equal(validatePlacement(s,x),null);});
test('partial progress preserves remaining block for the next subject turn',()=>{let s=fixture(3);for(let i=0;i<3;i++)s=goal(s,{subjectId:`s${i}`,title:`Goal ${i}`,totalSlides:300});const first=blocks(s)[0],count=first.slideEnd-first.slideStart+1;assert.ok(count>2);s=applyAction(s,{type:'start',id:first.id},at(first.date,first.start));s=applyAction(s,{type:'finish',complete:false,slidesCompleted:2,extra:30},at(first.date,first.end));assert.equal(s.goals[0].completedSlides,2);const upcoming=s.sessions.filter(x=>x.status==='planned'&&x.type==='study');assert.deepEqual(upcoming.slice(0,3).map(x=>x.subjectId),['s1','s2','s0']);assert.equal(blocks(s)[0].slideStart,3);assert.equal(blocks(s)[0].slideEnd,first.slideEnd);assert.equal(blocks(s)[0].end-blocks(s)[0].start,30);coverage(s);});
test('a finished block advances slide progress without prematurely completing the goal',()=>{let s=goal(fixture());const first=blocks(s)[0];s=applyAction(s,{type:'start',id:first.id},at(first.date,first.start));s=applyAction(s,{type:'finish',complete:true},at(first.date,first.end));assert.equal(s.goals[0].completedSlides,first.slideEnd);assert.equal(s.topics[0].status,'pending');coverage(s);});
test('fewer slides than available sessions never makes empty slide blocks',()=>{const s=goal(fixture(),{totalSlides:3,startSlide:8});assert.equal(blocks(s).length,3);coverage(s);});
test('no availability produces an explicit goal warning',()=>{const base=fixture();base.settings.days.forEach(d=>d.slots=[]);const s=goal(base);assert.equal(blocks(s).length,0);assert.match(s.notices.join(' '),/120 slides have no study time/);});
test('missed blocks are retained as history and their slides are redistributed',()=>{let s=goal(fixture());const first=blocks(s)[0];s=applyAction(s,{type:'plan'},at(first.date,first.start+12));assert.equal(s.sessions.find(x=>x.id===first.id).status,'missed');coverage(s);});
test('active range survives replan and editing an active goal is rejected',()=>{let s=goal(fixture());const first=blocks(s)[0];s=applyAction(s,{type:'start',id:first.id},at(first.date,first.start));s=applyAction(s,{type:'plan'},at(first.date,first.start+1));assert.equal(s.sessions.find(x=>x.id===first.id).slideEnd,first.slideEnd);assert.equal(blocks(s)[0].slideStart,first.slideEnd+1);assert.throws(()=>goal(s,{id:s.goals[0].id}),/active slide session/);});
test('a future start date does not block another ready goal of the same subject',()=>{let s=goal(fixture(),{startDate:addDays(today,3),deadline:addDays(today,4)});s=goal(s,{title:'Ready now',deadline:addDays(today,7)});assert.equal(s.sessions.find(x=>x.type==='study').date,today);assert.equal(s.sessions.find(x=>x.type==='study').goalId,s.goals[1].id);});
test('edits and archive keep completed history',()=>{let s=goal(fixture());const first=blocks(s)[0];s=applyAction(s,{type:'start',id:first.id},at(first.date,first.start));s=applyAction(s,{type:'finish',complete:true},at(first.date,first.end));s=applyAction(s,{type:'goal',...s.goals[0],totalSlides:180,deadline:addDays(today,15)},at(first.date,first.end));coverage(s);s=applyAction(s,{type:'archive-goal',id:s.goals[0].id},at(first.date,first.end));assert.equal(blocks(s).length,0);assert.equal(s.sessions.find(x=>x.id===first.id).status,'completed');});
test('invalid counts, dates, partial progress, and out of order starts are rejected',()=>{assert.throws(()=>goal(fixture(),{totalSlides:1.5}),/whole numbers/);assert.throws(()=>goal(fixture(),{deadline:'2026-02-30'}));let s=goal(fixture());const second=blocks(s)[1];assert.throws(()=>applyAction(s,{type:'start',id:second.id},at(today,second.start)),/earliest unfinished/);const first=blocks(s)[0];s=applyAction(s,{type:'start',id:first.id},at(today,first.start));assert.throws(()=>applyAction(s,{type:'finish',complete:false,slidesCompleted:100000},at(today,first.end)),/completed slide count/);});
test('final block completes goal and old backups migrate safely',()=>{let s=goal(fixture(),{totalSlides:1,deadline:today});const first=blocks(s)[0];s=applyAction(s,{type:'start',id:first.id},at(today,first.start));s=applyAction(s,{type:'finish',complete:true},at(today,first.end));assert.equal(s.goals[0].completedSlides,1);assert.equal(s.topics[0].status,'done');assert.equal(blocks(s).length,0);const old=fixture();delete old.goals;assert.deepEqual(validateState(old).goals,[]);});
